### ISSUE TITLE
你这个会持久更新吗？

### ISSUE THREAD

**Issue by sshien** [SatansTeam/STRouter#1]
如果你这个工具库不持久更新，我怎么用呢

**Comment by wliu6** [comment]
会持续不断更新的 @sshien ，这是个团队项目，不仅仅是我在做哟。使用发现问题欢迎随时提issue或pr

**Comment by wliu6** [comment]
> 如果你这个工具库不持久更新，我怎么用呢

会持续不断更新的 @sshien ，这是个团队项目，不仅仅是我在做哟。使用发现问题欢迎随时提issue或pr
